// <auto-generated />
using System;
using InventoryManagementSystemAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventoryManagementSystemAPI.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("InventoryManagementSystemAPI.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5fca3371-6f9f-4a0d-99a4-83df3fa34d66"),
                            Barcode = "0",
                            DateAdded = new DateTime(2021, 1, 23, 11, 41, 20, 148, DateTimeKind.Local).AddTicks(3554),
                            Name = "Item 1",
                            UserId = 0
                        },
                        new
                        {
                            Id = new Guid("5ffff381-a8e1-4faf-b059-79eb0a64ddc0"),
                            Barcode = "1",
                            DateAdded = new DateTime(2021, 1, 23, 11, 41, 20, 152, DateTimeKind.Local).AddTicks(8530),
                            Name = "Item 2",
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("a1fee671-6e34-4d2e-9f2e-d4eb0256cf39"),
                            Barcode = "2",
                            DateAdded = new DateTime(2021, 1, 23, 11, 41, 20, 152, DateTimeKind.Local).AddTicks(8565),
                            Name = "Item 3",
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
