// <auto-generated />
using System;
using InventoryManagementSystemAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventoryManagementSystemAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210125075748_BarcodeValidation")]
    partial class BarcodeValidation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("InventoryManagementSystemAPI.Data.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b8bfde2-7110-4814-9366-6e8c1ed49236"),
                            Barcode = "0",
                            DateAdded = new DateTime(2021, 1, 25, 8, 57, 47, 842, DateTimeKind.Local).AddTicks(2853),
                            Name = "Item 1",
                            UserId = 0
                        },
                        new
                        {
                            Id = new Guid("ec99dfa9-8f7b-409c-a98e-4d316462b347"),
                            Barcode = "1",
                            DateAdded = new DateTime(2021, 1, 25, 8, 57, 47, 847, DateTimeKind.Local).AddTicks(1405),
                            Name = "Item 2",
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("8d3afcfd-39dd-4c9d-abfa-1d072cc63700"),
                            Barcode = "2",
                            DateAdded = new DateTime(2021, 1, 25, 8, 57, 47, 847, DateTimeKind.Local).AddTicks(1465),
                            Name = "Item 3",
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
