// <auto-generated />
using System;
using InventoryManagementSystemAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventoryManagementSystemAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("InventoryManagementSystemAPI.Data.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7dbc38dc-c7cf-4b3d-91a3-60913f00112a"),
                            Barcode = "0",
                            DateAdded = new DateTime(2021, 1, 23, 14, 42, 11, 82, DateTimeKind.Local).AddTicks(2320),
                            Name = "Item 1",
                            UserId = 0
                        },
                        new
                        {
                            Id = new Guid("fab75011-08c4-495b-b86f-913b217fa342"),
                            Barcode = "1",
                            DateAdded = new DateTime(2021, 1, 23, 14, 42, 11, 86, DateTimeKind.Local).AddTicks(9706),
                            Name = "Item 2",
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("f077bf7b-4f83-474e-ae6d-786ce3237663"),
                            Barcode = "2",
                            DateAdded = new DateTime(2021, 1, 23, 14, 42, 11, 86, DateTimeKind.Local).AddTicks(9742),
                            Name = "Item 3",
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
